server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/dbc
    username: dbc
    password: secret
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect